version: "3.3"
services:
   backend:
     container_name: backend
     build: ./backend
     env_file:
       - ./backend/.env.sample
     ports:
       - "5000:5000"
     depends_on:
       - mongodb
   mongodb:
     container_name: mongo
     image: mongo:latest
     volumes:
       - ./backend/data:/data
     ports:
       - "27017:27017"
   forntend:
     container_name: frontend
     build: ./frontend
     env_file:
       - ./backend/.env.sample
     ports:
       - "5173:5173"


volumes:
  data:
