name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: unbuntu:latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
  deploy:
    runs-on: aws_ec2
    steps:
      - name: down
        run: docker-compose down wanderlust/
      - name: up
        run: docker-compose up wanderlust/
