name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: unbuntu:latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
  deploy:
    runs-on: aws_ec2
    steps:
      - uses: actions/checkout@v3
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./WANDERLUST/docker-compose.yml"
