name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: aws_ec2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: running the docker
      run: sudo systemctl start docker

    - name: Deploy with Docker Compose
      run: |
        cd /home/ubuntu/actions-runner/_work/wanderlust/wanderlust
        sudo docker-compose down
        sudo docker-compose up -d
