name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: unbuntu:latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: up
        run: docker-compose up -d
  deploy:
    runs-on: aws_ec2
  
